### ISSUE TITLE
app won't build after following README steps

### ISSUE THREAD

**Issue by juanmanuelbouvier** [Nexmo/stitch-demo#5]
Hi!
This is the first time I ever open an issue in a public repository, so excuse me if there is some missing info that you need. Please, let me know if that is the case.

I am new to Nexmo platform. I want to explore the Stitch functionalities with my 'Try it free' account.
I followed the steps specified in the README, but the command "npm start" does not work for me.
It throws this error:

`        throw new Error("File \"" + privateKey + "\" not found.");
        ^

Error: File "" not found.
    at new Credentials (/Users/juanmanuel.bouvier/Almundo/nexmo/stitch-demo/node_modules/nexmo/lib/Credentials.js:49:15)
    at Function.parse (/Users/juanmanuel.bouvier/Almundo/nexmo/stitch-demo/node_modules/nexmo/lib/Credentials.js:104:16)
    at new Nexmo (/Users/juanmanuel.bouvier/Almundo/nexmo/stitch-demo/node_modules/nexmo/lib/Nexmo.js:119:46)
    at Object.<anonymous> (/Users/juanmanuel.bouvier/Almundo/nexmo/stitch-demo/routes/api.js:9:13)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)` 

I think there is something wrong with my example.env but I don't know what could it be. I inserted my own API_KEY, API_SECRET and APP_ID as the README says.
I created the app once the repo was cloned, so I have all nexmo files in that same directory. I copied the app creation command as it is.

BTW I couldn't find the private.key.example file in the repo.

¿Any ideas?

**Comment by juanmanuelbouvier** [comment]
Thanks for your answer!
Unfortunately, the app still does not run. I tried downgrading node via nvm to version 6, but the same error remains.

**Comment by ericgiannini** [comment]
Did you try version 9?
